### ISSUE TITLE
Missing dependency - jQuery and /files/ path

### ISSUE THREAD

**Issue by SkepticalTrueBeliever** [amirchev/OBS-OpenLP-Lyrics-Interface#1]
Both control.html and stage.html refer to
<script type="text/javascript" src="/files/jquery.min.js"></script>

Which version of jquery.min.js is required?

How about moving all dependencies into this same directory?

**Comment by amirchev** [comment]
This tool is a stage for the OpenLP Remote plugin. Those links to jQuery and other resources in the /pages directory will exist when OpenLP links them internally. Are you getting errors?

**Comment by SkepticalTrueBeliever** [comment]
I get a blank page with just a small (about 1 cm^2) grey square in the middle.

I'm using this with OpenLP 2.4.6.

**Comment by amirchev** [comment]
Yes, your browser source will display that small box when there are no lyrics to display. You can consider it a known bug. I have not gotten around to fixing it (it's due to the padding of the lyrics div). Make sure you have a live slide on OpenLP AND that you have received the text in the control. Click display next and it should appear.

**Comment by SkepticalTrueBeliever** [comment]
I do have a set of live slides cycling. I can see them in other browser windows connected to /main and /stage, as well as on the connected projector.

**Comment by amirchev** [comment]
Does the text pop up in the preview in the control.html?

**Comment by SkepticalTrueBeliever** [comment]
When I create a browser source for http://_ipaddress_:4316/stage/stream, the only thing that show is the preview is that small square grey square. Is this what you were asking? I haven't specified control.html in the path.

**Comment by amirchev** [comment]
Yes, you need to also add a custom browser dock to control what part of the slide is displayed. Otherwise nothing will be displayed in the browser source.

**Comment by amirchev** [comment]
I added a new guide, btw, that may be helpful.

https://obsproject.com/forum/resources/using-openlp-interface-for-lyrics.1009/
