### ISSUE TITLE
Feature Request - Text Formatting

### ISSUE THREAD

**Issue by Lordi91** [amirchev/OBS-OpenLP-Lyrics-Interface#11]
Love the stage plugin - saved me from having to look into it myself!

Was wondering if its possible to show the formatting within it - we do a lot of say and response stuff and a few people have commented online that they arnt sure which bit is for them and which isnt - and our leaders arnt a fan of me putting "all:" at the start of bits they are to respond with

Thanks

**Comment by amirchev** [comment]
How exactly do you format it?

**Comment by amirchev** [comment]
Hi, please see [v1.3.1](https://github.com/amirchev/OBS-OpenLP-Lyrics-Interface/releases/tag/v1.3.1) for added formatting carryover from OpenLP.
