### ISSUE TITLE
Add an option to hide the subtitles

### ISSUE THREAD

**Issue by cgonzalez** [amirchev/OBS-OpenLP-Lyrics-Interface#2]
Please add an option to hide the subtitles when OpenLP is in "Show Desktop", "Show Theme" or "Blank" mode.

Right now, the only way I've found to temporarily hide the subtitles is to hide the browser in the "Sources" panel in OBS. This is very uncomfortable and error prone (the "hide source" button in OBS is very small).

BTW thank you for this great OpenLP plugin :-)

**Comment by amirchev** [comment]
Hi, great suggestion, I will put that in with the next release. One thing you can do in the meanwhile is add a hotkey to hide/show your browser source, which will make it much easier for you in the future. I will add the button just in case someone else wants to use it as well.

**Comment by amirchev** [comment]
See version [1.1.0](https://github.com/amirchev/OBS-OpenLP-Lyrics-Interface/releases/tag/v1.1.0), thanks!
