### ISSUE TITLE
Tool not working with openlp 2.9.5

### ISSUE THREAD

**Issue by cotgk** [amirchev/OBS-OpenLP-Lyrics-Interface#27]
Run this tool successfully on openlp2.4.6 but seems there's a disconnect with openlp 2.9.5. Please do you know why?

**Comment by amirchev** [comment]
Unfortunately, the plugin this tool used to communicate with OpenLP may no longer be supported. I have not had a chance to look into it. I will comment back once I have.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: cotgk ***@***.***>
Sent: Sunday, September 18, 2022 7:16:19 AM
To: amirchev/OBS-OpenLP-Lyrics-Interface ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amirchev/OBS-OpenLP-Lyrics-Interface] Tool not working with openlp 2.9.5 (Issue #27)


Run this tool successfully on openlp2.4.6 but seems there's a disconnect with openlp 2.9.5. Please do you know why?

**Comment by tdi2004** [comment]
Alexander, do you see any chance in future to get this interface working with openLP > 2.9?

**Comment by LibertatisPrius** [comment]
I would love it if this could be made to work with OpenLP 3.0. We just upgraded and have had to abandon this tool for the time being.

> Unfortunately, the plugin this tool used to communicate with OpenLP may no longer be supported. I have not had a chance to look into it. I will comment back once I have. Get Outlook for Android<https://aka.ms/AAb9ysg>

If you are referring to the Remote plugin, it still is supported, it just has been unbundled from OpenLP to allow for easier updates. They warn the old APIs will be dropped at some point though.

Thank you for the work you've put into this!

**Comment by amirchev** [comment]
Happy to report the API this tool uses is still in place and works well as of v1.4.3 after some minor tweaks. God bless.!
