### ISSUE TITLE
Please provide option to select previous line in slide

### ISSUE THREAD

**Issue by wisdomofchristchurch** [amirchev/OBS-OpenLP-Lyrics-Interface#4]
Hello,

Firstly thanks for your interface.

That helped us a lot, if possible can u modify the code in such a way that either text is selectable or option to go to previous line in the selected slide where we have 2-4 lines 

and there is no option to either select next slide directly from obs so we need to manually interchange the slides 

if the choir sings the song repeatedly

Please never mind and help us in this 

Thanks in advance !!!

**Comment by amirchev** [comment]
Hello, I will make it so that you can go to previous slide, but it will not be possible to go to the next slide, since OpenLP does not allow for it.

**Comment by amirchev** [comment]
> 
> 
> Hello, I will make it so that you can go to previous slide, but it will not be possible to go to the next slide, since OpenLP does not allow for it.

Although, let me look into it, it may be doable.

**Comment by amirchev** [comment]
All done, please see [this release](https://github.com/amirchev/OBS-OpenLP-Lyrics-Interface/releases/tag/v1.2.0).
