### ISSUE TITLE
1.2.0 release seems to be a bit green yet

### ISSUE THREAD

**Issue by mdarbonis** [amirchev/OBS-OpenLP-Lyrics-Interface#7]
At least I didn't manage to get anything else than the small grey square. I use Windows 10 and OBS 26.1.1 64 bit, OpenLP 2.4.6. After adding a separate BroadcastChannel instance for receiving messages and somewhat modifying text processing in channelReceive function in stage.js it displays the texts. Paging still seems to work only in the control dock but not in actual video output.
Please check when you have the time and thanks for a useful tool.

[stage.zip](https://github.com/amirchev/OBS-OpenLP-Lyrics-Interface/files/6079609/stage.zip)

**Comment by amirchev** [comment]
You're right, I just realized I tested in the browser and it worked, but I don't think I ever went back to OBS. I guess the text length code was buggy. I didn't use your fix but it helped me narrow down where to look. Please look at [1.2.1](https://github.com/amirchev/OBS-OpenLP-Lyrics-Interface/releases/tag/v1.2.1).

**Comment by mdarbonis** [comment]
Yes, works now, thanks a lot.
